### ISSUE TITLE
Support floor type 0

### ISSUE THREAD

**Issue by est31** [est31/lewton#1]
Nobody actually uses it anymore, but it still would be nice to have.

Anyone got example files?

**Comment by bungcip** [comment]
https://bitbucket.org/achurch_/libnogg have floor0 ogg in tests folder.

**Comment by est31** [comment]
Cool, what I needed. Thanks!

**Comment by est31** [comment]
Mhh, seems I didn't get it working. Would be cool if someone could extract some few test data from an implementation where the floor 0 is working: https://gist.github.com/est31/a36a48197f4141c67f64218911f3f3fa
