### ISSUE TITLE
Non blocking reads

### ISSUE THREAD

**Issue by plietar** [est31/lewton#6]
It would be great if lewton and the ogg crate supported non blocking sources.

Essentially, if the underlying `io::Read` returns a `WouldBlock` error, the error should be propagated but making sure the decoder is left in a consistent state.

At the moment, a with quick test with a stream which randomly returns `WouldBlock`, lewton fails to recover, returning various errors (`HeaderIsAudio`, `InvalidData`, panics, ...)

In [librespot](https://github.com/plietar/librespot) I stream an ogg file using libvorbis, and currently have to block my player thread when waiting for data. The initial setup can take a few seconds until enough data is ready to start playing. I'm planning to move the initial load to a separate thread, but non blocking support in the decoder would be a better solution.

**Comment by est31** [comment]
Interesting. Can you share the test code? If its possible to do without additional dependencies like mio, I'll attempt a fix.

**Comment by plietar** [comment]
This is what I tried, based on the example code : 
https://gist.github.com/plietar/efcf6bc5a38b98ad14f5716fb1d6eb83
Read / seeks will fail with a 50% chance of getting a `WouldBlock` error.

This shouldn't require any external dependencies. If lewton/ogg gets such an error, it needs to propagate it to the original caller, while making sure the same function can be invoked again to make more progress. This would then be trivial to wrap in any async IO library (I have futures-rs in mind, but it should be generic).

It currently propagates the error correctly, but all IO errors are treated the same, and considered fatal, so no recovery is possible. Attempts to retry the function call fail since the decoder was left in an inconsistent state.

I haven't looked at the internals yet, so I have no idea how much work this would involve. The vorbis decoder should be pretty much unchanged, it's mostly about the ogg crate (sorry, I should probably open this issue there).

Thanks !

**Comment by est31** [comment]
Yeah its mostly an issue about the ogg crate, but the inside_ogg module of this crate should be affected as well.

Its a bit tricky as I'm using read_exact atm in the ogg crate which eats the data if it returns an err. Maybe I have to write my own version of it...

**Comment by est31** [comment]
Okay, I've got it working. See the last few commits from the two repositories. You can now see an example of how to access the async api in the `async_decoder` example. It can be invoked like:

`cargo run --release --features async_ogg --example async_decoder /path/to/your/file.ogg`

But note that it only does the decoding part, not the playback.

If you want a new release so that its on crates.io for use in your own crates, please say so.

**Comment by plietar** [comment]
Thanks for implementing this. I only just got around to actually trying this and it worked like a charm (just like the rest of the crate).
I was easily able to make a wrapper around it for futures-rs : https://github.com/plietar/librespot/blob/e67a540/src/ogg_async.rs

Requiring nightly is a problem for me though. Would you consider either always wrapping the stream in a `BufReader` (at least when the `async` feature is enabled). The performance cost shouldn't be significant ?

I can make a PR for that's an acceptable trade of.

**Comment by est31** [comment]
@plietar if the async feature is enabled, one could always wrap in BufReader, yes. A PR would be welcome :). When making it don't forget to set your editor to tabs only, as the codebases use tabs (saying this as 90% of rust codebases don't use tabs for indentation).

**Comment by est31** [comment]
@plietar I have pushed https://github.com/RustAudio/ogg/commit/0465f746612b3a38a0250390b510e8014da6bab1 with a true futures-rs based ogg packet reading struct. A quite nice feature is that it doesn't require nightly. Everything will be improved a bit and maybe I'll also add seeking support before publishing a version.

Note though that for the upcoming version of the ogg crate you'll need at least Rust 1.17, which is currently in beta. The upcoming version of lewton will even require Rust 1.18 (which is nightly atm). But I plan that I won't raise the required version number soon. Just for ogg I wanted to use field init shorthands, and for lewton I wanted pub(restricted).
